spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/data_jpa
    username: dockerpostgre
    password: romazal
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true